# Generated by Django 2.2.4 on 2019-08-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.NullBooleanField(default=None, verbose_name='Новостройка'),
        ),
    ]
