# Generated by Django 2.2.4 on 2019-08-15 15:20

from django.db import migrations


def update_new_building(apps, schema_editor):
    flat_model = apps.get_model('property', 'Flat')
    for flat in flat_model.objects.all():
        flat.new_building = True if flat.construction_year >= 2015 else False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(update_new_building)
    ]
