# Generated by Django 2.2.4 on 2019-08-15 16:52

from django.db import migrations

from phonenumbers import format_number, parse, PhoneNumberFormat, is_valid_number


def create_owner_phone_pure(apps, schema_editor):
    flat_model = apps.get_model('property', 'Flat')
    for flat in flat_model.objects.all():
        parse_number = parse(flat.owners_phonenumber, "RU")
        if is_valid_number(parse_number):
            flat.owner_phone_pure = format_number(parse_number, PhoneNumberFormat.E164)
        else:
            flat.owner_phone_pure = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20190815_1943'),
    ]

    operations = [
        migrations.RunPython(create_owner_phone_pure)
    ]
