# Generated by Django 2.2.4 on 2019-08-15 17:50

from django.db import migrations


def create_owner_phone_pure(apps, schema_editor):
    flat_model = apps.get_model('property', 'Flat')
    owner_model = apps.get_model('property', 'Owner')
    for flat in flat_model.objects.all():
        owner_model.objects.get_or_create(owner=flat.owner_deprecated,
                                          owners_phonenumber=flat.owners_phonenumber,
                                          owner_phone_pure=flat.owner_phone_pure, )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_owner'),
    ]

    operations = [
        migrations.RunPython(create_owner_phone_pure)
    ]
