# Generated by Django 2.2.4 on 2019-08-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_owner'),
    ]

    operations = [
    ]
