# Generated by Django 2.2.4 on 2019-08-15 18:06

from django.db import migrations


def create_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete()
    for flat in Flat.objects.all():
        new_owner = Owner(owner=flat.owner_deprecated, owners_phonenumber=flat.owners_phonenumber, owner_phone_pure=flat.owner_phone_pure)
        new_owner.save()
        new_owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20190815_2106'),
    ]

    operations = [
        migrations.RunPython(create_owner)
    ]
