# Generated by Django 2.2.4 on 2019-08-15 18:06

from django.db import migrations


def create_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(owner=flat.owner_deprecated,
                                            owners_phonenumber=flat.owners_phonenumber,
                                            owner_phone_pure=flat.owner_phone_pure)
        if created:
            owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20190815_2050'),
    ]

    operations = [
        migrations.RunPython(create_owner)
    ]
